### ISSUE TITLE
LUA Errors

### ISSUE THREAD

**Issue by Arcaila** [peterwooley/Todo#1]
Got 109 of these, all the same save for a variation on missing entry. No other addons enabled:

Message: AceLocale-3.0: Todo: Missing entry for 'Show/Hide the To-Do List'
Time: Sat May 21 03:31:43 2022
Count: 1
Stack: AceLocale-3.0: Todo: Missing entry for 'Show/Hide the To-Do List'
[string "@Interface\AddOns\Todo\Assets\Scripts\config.lua"]:25: in main chunk

Locals: <none>

**Comment by peterwooley** [comment]
Hey! 
Reviewing the locale support, there looks to be a build issue but I have yet to figure it out. Can I get a bit more info to see if I can reproduce it?

* Did this happen on the first run of the addon or did it happen after you'd already used it?
* Which locale are you using for WoW (US English or something else)?

Thanks!

**Comment by Arcaila** [comment]
I had not used it yet. Trying to recall the specific timeframe at this point. I know I disabled all add-ons to make sure it wasn't a conflict. I want to say I had no issues initially, but maybe it started after an update? I had only started using the addon recently.

The locale is US English.

Hope this helps.

Regards,

Holly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peterwooley** [comment]
I've fixed how locale files are loaded and I believe I addressed the issue, but it was messed up during packaging on CurseForge so if you could [update to the 1.0.4 version](https://www.curseforge.com/wow/addons/todo/files/3823803) and see if it fixes it, that'd be a great help!

**Comment by Arcaila** [comment]
Will do. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Arcaila** [comment]
Installed newest version and tested. Even with all my add-ons it worked perfectly. Thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peterwooley** [comment]
Terrific! Thanks for verifying!
